### ISSUE TITLE
Poor Performance on Mobile Device

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#46]
Extremely poor performance on mobile devices. Need time to investigate the root cause. 

- It is highly possible that the `Filesystem` on the Android device is not fast enough to rapidly query multiple times.
  - Possible fix: merge the information tuples into a large json file.
  - Possible fix: use sqlite instead.
- Media data use base64 encoding to pass around instead of file object with source URI.

## Roadmap

- [x] ~~Use `<img />` instead of `<ion-img>` for better performance.~~
- [x] ~~Merge the information tuples into a large json file.~~ This require new "equal" class to check the equality. Greatly add complexity.
- [x] Call `Storage.refresh$()` only on initialization.
  - [x] Remove calling `Storage.refresh$()` on `Storage.add$()`.
  - [x] ~~Remove calling `Storage.refresh$()` on `Storage.remove$()`.~~ This require new "equal" class to check the equality. Greatly add complexity.
- [x] Generate the thumbnail of the media asset on captured.
